"use client";

import {useEffect, useState} from "react";
import {Box, Plus, Trash2} from "lucide-react";
import * as adminApi from "@/lib/admin/api";
import type {
    OrderBoxResponse,
    OrderLine,
    OrderResponse,
    ReplaceBoxesRequest,
} from "@/lib/admin/types";
import {DEFAULT_BOX_HEIGHT_IN, DEFAULT_BOX_LENGTH_IN, DEFAULT_BOX_WIDTH_IN} from "@/lib/admin/types";
import {ApiError} from "@/lib/api";
import {useNotifications} from "@/components/notifications/notification-store";

type DraftBox = {
    key: string;
    lengthIn: string;
    widthIn: string;
    heightIn: string;
    weightGrams: string;
    /** True until the admin edits the weight field directly - keeps it synced to the
     * assigned items' known variant weight. Cleared permanently on the first manual edit. */
    weightAuto: boolean;
    label: string;
    /** orderItemId -> quantity assigned to this box */
    assignments: Record<number, number>;
};

let nextKey = 1;

function newDraftBox(): DraftBox {
    return {
        key: `box-${nextKey++}`,
        lengthIn: String(DEFAULT_BOX_LENGTH_IN),
        widthIn: String(DEFAULT_BOX_WIDTH_IN),
        heightIn: String(DEFAULT_BOX_HEIGHT_IN),
        weightGrams: "0",
        weightAuto: true,
        label: "",
        assignments: {},
    };
}

/** Sum of assigned items' known unit weight * quantity; unweighed variants contribute 0. */
function computeAutoWeight(assignments: Record<number, number>, items: OrderLine[]): number {
    return items.reduce((sum, line) => {
        const qty = assignments[line.id] ?? 0;
        return sum + qty * (line.unitWeightGrams ?? 0);
    }, 0);
}

/**
 * Fulfillment / packing stage inserted between order processing and
 * shipping (client requirement, 2026-08). Admin groups a few order lines
 * into a box with real dimensions/weight; anything left unassigned ships
 * "as is" in its own original packaging - the backend auto-boxes those.
 */
export function OrderPackPanel({
                                    order,
                                    onPacked,
                                }: {
    order: OrderResponse;
    onPacked: (order: OrderResponse) => void;
}) {
    const notifications = useNotifications();
    const [savedBoxes, setSavedBoxes] = useState<OrderBoxResponse[] | null>(null);
    const [draftBoxes, setDraftBoxes] = useState<DraftBox[]>([]);
    const [saving, setSaving] = useState(false);

    useEffect(() => {
        adminApi
            .getOrderBoxes(order.orderNumber)
            .then((boxes) => {
                setSavedBoxes(boxes);
                const manual = boxes.filter((box) => !box.autoGenerated);
                setDraftBoxes(
                    manual.map((box) => ({
                        key: `box-${box.id}`,
                        lengthIn: String(box.lengthIn),
                        widthIn: String(box.widthIn),
                        heightIn: String(box.heightIn),
                        weightGrams: String(box.weightGrams),
                        // Already a real saved value, not a suggestion - don't overwrite it
                        // if the admin merely reopens the order without touching assignments.
                        weightAuto: false,
                        label: box.label ?? "",
                        assignments: Object.fromEntries(
                            box.items.map((item) => [item.orderItemId, item.quantity]),
                        ),
                    })),
                );
            })
            .catch(() => setSavedBoxes([]));
    }, [order.orderNumber]);

    const canPack =
        ["PROCESSING", "PACKED"].includes(order.status) ||
        (order.pricingGroup === "DISTRIBUTOR" &&
            ["AWAITING_PAYMENT_VERIFICATION", "PLACED", "PENDING_PAYMENT"].includes(order.status));

    if (!canPack) {
        return null;
    }

    function assignedFor(orderItemId: number, excludeBoxKey?: string) {
        return draftBoxes
            .filter((box) => box.key !== excludeBoxKey)
            .reduce((sum, box) => sum + (box.assignments[orderItemId] ?? 0), 0);
    }

    function remainingFor(orderItemId: number, quantity: number, excludeBoxKey?: string) {
        return quantity - assignedFor(orderItemId, excludeBoxKey);
    }

    function updateAssignment(boxKey: string, orderItemId: number, quantity: number) {
        setDraftBoxes((boxes) =>
            boxes.map((box) => {
                if (box.key !== boxKey) return box;
                const assignments = {...box.assignments};
                if (quantity <= 0) {
                    delete assignments[orderItemId];
                } else {
                    assignments[orderItemId] = quantity;
                }
                return {
                    ...box,
                    assignments,
                    // Keep the weight suggestion in sync as items are assigned/removed,
                    // unless the admin already typed a weight themselves.
                    weightGrams: box.weightAuto
                        ? String(computeAutoWeight(assignments, order.items))
                        : box.weightGrams,
                };
            }),
        );
    }

    function updateBoxWeight(key: string, value: string) {
        setDraftBoxes((boxes) =>
            boxes.map((box) =>
                box.key === key ? {...box, weightGrams: value, weightAuto: false} : box,
            ),
        );
    }

    function addBox() {
        setDraftBoxes((boxes) => [...boxes, newDraftBox()]);
    }

    function removeBox(key: string) {
        setDraftBoxes((boxes) => boxes.filter((box) => box.key !== key));
    }

    function updateBoxField(key: string, field: "lengthIn" | "widthIn" | "heightIn" | "label", value: string) {
        setDraftBoxes((boxes) =>
            boxes.map((box) => (box.key === key ? {...box, [field]: value} : box)),
        );
    }

    const unassignedCount = order.items.reduce(
        (sum, line) => sum + Math.max(0, remainingFor(line.id, line.quantity)),
        0,
    );

    async function savePacking() {
        setSaving(true);
        try {
            const payload: ReplaceBoxesRequest = {
                boxes: draftBoxes
                    .filter((box) => Object.keys(box.assignments).length > 0)
                    .map((box) => ({
                        lengthIn: Number(box.lengthIn) || DEFAULT_BOX_LENGTH_IN,
                        widthIn: Number(box.widthIn) || DEFAULT_BOX_WIDTH_IN,
                        heightIn: Number(box.heightIn) || DEFAULT_BOX_HEIGHT_IN,
                        weightGrams: Math.max(0, Number(box.weightGrams) || 0),
                        label: box.label.trim() || null,
                        items: Object.entries(box.assignments)
                            .filter(([, qty]) => qty > 0)
                            .map(([orderItemId, quantity]) => ({
                                orderItemId: Number(orderItemId),
                                quantity,
                            })),
                    })),
            };
            const result = await adminApi.packOrder(order.orderNumber, payload);
            setSavedBoxes(result.boxes);
            if (result.order) {
                onPacked(result.order);
            }
            notifications.success(
                "Order packed",
                `${result.boxes.length} box(es) recorded; ready to ship.`,
            );
        } catch (err) {
            notifications.error("Packing failed", err instanceof ApiError ? err.message : "Packing failed.");
        } finally {
            setSaving(false);
        }
    }

    const overAllocated = order.items.some((line) => remainingFor(line.id, line.quantity) < 0);

    return (
        <div className="rounded-2xl bg-white p-5 shadow-card">
            <div className="flex items-center gap-2">
                <Box className="size-4 text-teal-950" aria-hidden/>
                <h2 className="text-[15px] font-bold text-teal-950">Pack order</h2>
            </div>
            <p className="mt-1 text-[12px] text-muted">
                Group items into boxes for shipping. Anything left unassigned ships as-is in its own
                original packaging.
            </p>

            <div className="mt-4 space-y-2">
                {order.items.map((line) => {
                    const remaining = remainingFor(line.id, line.quantity);
                    return (
                        <div
                            key={line.id}
                            className="flex items-center justify-between gap-3 rounded-xl bg-soft-control px-3 py-2 text-[13px]"
                        >
                            <div className="min-w-0">
                                <p className="truncate font-semibold text-teal-950">{line.productName}</p>
                                <p className="text-[11px] text-muted">{line.sku} · qty {line.quantity}</p>
                            </div>
                            <span
                                className={`shrink-0 text-[11px] font-bold ${
                                    remaining < 0 ? "text-coral" : remaining === 0 ? "text-teal-700" : "text-muted"
                                }`}
                            >
                {remaining === 0 ? "fully boxed" : remaining < 0 ? "over-assigned" : `${remaining} ships as-is`}
              </span>
                        </div>
                    );
                })}
            </div>

            <div className="mt-4 space-y-3">
                {draftBoxes.map((box, index) => (
                    <div key={box.key} className="rounded-xl border border-black/10 p-3">
                        <div className="flex items-center justify-between gap-2">
                            <p className="text-[13px] font-bold text-teal-950">Box {index + 1}</p>
                            <button
                                type="button"
                                onClick={() => removeBox(box.key)}
                                className="grid size-7 place-items-center rounded-full text-muted transition-colors hover:bg-coral/10 hover:text-coral"
                                aria-label="Remove box"
                            >
                                <Trash2 className="size-3.5" aria-hidden/>
                            </button>
                        </div>

                        <div className="mt-2 grid grid-cols-4 gap-2">
                            <label className="text-[11px] text-muted">
                                Length (in)
                                <input
                                    type="number"
                                    min="0"
                                    step="0.5"
                                    value={box.lengthIn}
                                    onChange={(e) => updateBoxField(box.key, "lengthIn", e.target.value)}
                                    className="mt-1 h-9 w-full rounded-lg border border-black/10 px-2 text-[13px] outline-none focus:border-teal-950"
                                />
                            </label>
                            <label className="text-[11px] text-muted">
                                Width (in)
                                <input
                                    type="number"
                                    min="0"
                                    step="0.5"
                                    value={box.widthIn}
                                    onChange={(e) => updateBoxField(box.key, "widthIn", e.target.value)}
                                    className="mt-1 h-9 w-full rounded-lg border border-black/10 px-2 text-[13px] outline-none focus:border-teal-950"
                                />
                            </label>
                            <label className="text-[11px] text-muted">
                                Height (in)
                                <input
                                    type="number"
                                    min="0"
                                    step="0.5"
                                    value={box.heightIn}
                                    onChange={(e) => updateBoxField(box.key, "heightIn", e.target.value)}
                                    className="mt-1 h-9 w-full rounded-lg border border-black/10 px-2 text-[13px] outline-none focus:border-teal-950"
                                />
                            </label>
                            <label className="text-[11px] text-muted">
                                Weight (g){box.weightAuto && <span className="text-teal-700"> · auto</span>}
                                <input
                                    type="number"
                                    min="0"
                                    step="10"
                                    value={box.weightGrams}
                                    onChange={(e) => updateBoxWeight(box.key, e.target.value)}
                                    className="mt-1 h-9 w-full rounded-lg border border-black/10 px-2 text-[13px] outline-none focus:border-teal-950"
                                />
                            </label>
                        </div>

                        <div className="mt-3 space-y-1.5">
                            {order.items.map((line) => {
                                const assigned = box.assignments[line.id] ?? 0;
                                const remainingOutsideThisBox = remainingFor(line.id, line.quantity, box.key);
                                const max = Math.max(assigned, remainingOutsideThisBox);
                                return (
                                    <div key={line.id} className="flex items-center justify-between gap-2 text-[12px]">
                                        <span className="min-w-0 truncate text-teal-950">{line.productName}</span>
                                        <input
                                            type="number"
                                            min="0"
                                            max={max}
                                            value={assigned}
                                            onChange={(e) =>
                                                updateAssignment(
                                                    box.key,
                                                    line.id,
                                                    Math.max(0, Math.min(max, Number(e.target.value) || 0)),
                                                )
                                            }
                                            className="h-8 w-16 shrink-0 rounded-lg border border-black/10 px-2 text-right text-[12px] outline-none focus:border-teal-950"
                                        />
                                    </div>
                                );
                            })}
                        </div>
                    </div>
                ))}

                <button
                    type="button"
                    onClick={addBox}
                    className="flex h-10 w-full items-center justify-center gap-1.5 rounded-xl border border-dashed border-black/15 text-[13px] font-bold text-teal-950 transition-colors hover:bg-soft-control"
                >
                    <Plus className="size-4" aria-hidden/>
                    Add box
                </button>
            </div>

            <p className="mt-3 text-[12px] text-muted">
                {unassignedCount > 0
                    ? `${unassignedCount} unit(s) will ship as-is in their own original packaging.`
                    : "Every unit is assigned to a box."}
            </p>

            <button
                type="button"
                disabled={saving || overAllocated}
                onClick={savePacking}
                className="mt-3 h-10 w-full rounded-xl bg-teal-950 text-[13px] font-bold text-white transition-colors hover:bg-teal-900 disabled:cursor-not-allowed disabled:opacity-40"
            >
                {saving ? "Saving…" : order.status === "PACKED" ? "Save & re-pack" : "Save & pack"}
            </button>

            {savedBoxes && savedBoxes.length > 0 && order.status === "PACKED" && (
                <p className="mt-2 text-[11px] text-muted">
                    Currently packed into {savedBoxes.length} box(es)
                    {savedBoxes.some((b) => b.autoGenerated) &&
                        ` (${savedBoxes.filter((b) => b.autoGenerated).length} shipping as-is)`}.
                </p>
            )}
        </div>
    );
}
