"use client";

import React, { useState, useEffect } from "react";
import { Printer, Download, ArrowLeft, Box, Truck, FileText, CheckCircle2, AlertTriangle, ShieldCheck, Phone, Mail, MapPin } from "lucide-react";
import { BarcodeSvg } from "@/components/common/barcode";
import type { OrderResponse, OrderBoxResponse } from "@/lib/admin/types";
import { getOrderBoxes } from "@/lib/admin/api";

interface ShippingLabelViewProps {
    order: OrderResponse;
    initialBoxes?: OrderBoxResponse[];
    defaultDocType?: "PARCEL" | "PALLET" | "BOL";
    onClose?: () => void;
}

export function ShippingLabelView({
    order,
    initialBoxes,
    defaultDocType,
    onClose,
}: ShippingLabelViewProps) {
    const isPalletShipment =
        order.shippingMethod?.toLowerCase().includes("pallet") ||
        order.shippingMethod?.toLowerCase().includes("skid") ||
        order.carrierName?.toLowerCase().includes("day") ||
        order.carrierName?.toLowerCase().includes("ross") ||
        order.carrierName?.toLowerCase().includes("ltl") ||
        order.pricingGroup === "DISTRIBUTOR" ||
        order.shippingTotal >= 140;

    const [docType, setDocType] = useState<"PARCEL" | "PALLET" | "BOL">(
        defaultDocType || (isPalletShipment ? "PALLET" : "PARCEL")
    );
    const [boxes, setBoxes] = useState<OrderBoxResponse[]>(initialBoxes || []);
    const [selectedBoxIndex, setSelectedBoxIndex] = useState<number>(-1); // -1 means "All"
    const [downloadingPdf, setDownloadingPdf] = useState(false);

    useEffect(() => {
        if (!initialBoxes || initialBoxes.length === 0) {
            getOrderBoxes(order.orderNumber)
                .then((res) => {
                    if (res && res.length > 0) {
                        setBoxes(res);
                    }
                })
                .catch(() => {});
        }
    }, [order.orderNumber, initialBoxes]);

    // Calculate effective weight
    const totalWeightKg = (
        boxes.length > 0
            ? boxes.reduce((sum, b) => sum + (b.weightGrams || 1000), 0) / 1000
            : order.items?.reduce((sum, item) => sum + ((item.unitWeightGrams || 1000) * (item.quantity || 1)), 0) / 1000
    ) || (isPalletShipment ? 250 : 2.5);

    const totalWeightLbs = (totalWeightKg * 2.20462).toFixed(1);

    // Fallback single box if none configured
    const displayBoxes = boxes.length > 0 ? boxes : [
        {
            id: 1,
            sequence: 1,
            boxNumber: 1,
            lengthIn: isPalletShipment ? 40 : 12,
            widthIn: isPalletShipment ? 48 : 10,
            heightIn: isPalletShipment ? 54 : 8,
            weightGrams: totalWeightKg * 1000,
            label: isPalletShipment ? "Standard 40x48 Pallet" : "Master Carton 1",
            autoGenerated: true,
            items: [],
        } as OrderBoxResponse,
    ];

    const trackingNum = order.trackingNumber || `WAT-${order.orderNumber}`;
    const carrier = order.carrierName || (isPalletShipment ? "Day & Ross LTL via Freightcom" : "Canada Post via Freightcom");
    const serviceName = order.shippingMethod || (isPalletShipment ? "Standard Pallet Freight" : "Expedited Parcel");
    const addr = order.shippingAddress || ({} as any);

    const destPostal = (addr.postalCode || "K1P 5N5").toUpperCase();
    const destCity = (addr.city || "Ottawa").toUpperCase();
    const destRegion = (addr.region || "ON").toUpperCase();
    const destCountry = (addr.country || "Canada").toUpperCase();

    const placedDate = order.placedAt
        ? new Date(order.placedAt).toLocaleDateString("en-CA")
        : new Date().toLocaleDateString("en-CA");

    function handlePrint() {
        window.print();
    }

    async function handleDownloadPdf() {
        setDownloadingPdf(true);
        try {
            const { default: jsPDF } = await import("jspdf");
            if (docType === "PARCEL") {
                // 4x6 inches label format (288 x 432 pt)
                const doc = new jsPDF({ unit: "pt", format: [288, 432] });
                const boxesToPrint = selectedBoxIndex === -1 ? displayBoxes : [displayBoxes[selectedBoxIndex]];

                boxesToPrint.forEach((box, idx) => {
                    if (idx > 0) doc.addPage([288, 432]);
                    const boxWtKg = ((box.weightGrams || 1000) / 1000).toFixed(1);
                    const boxWtLbs = (((box.weightGrams || 1000) / 1000) * 2.20462).toFixed(1);

                    // Header
                    doc.setFillColor(15, 45, 40);
                    doc.rect(0, 0, 288, 42, "F");
                    doc.setTextColor(255, 255, 255);
                    doc.setFont("helvetica", "bold");
                    doc.setFontSize(12);
                    doc.text("WATANI & SONS CORP", 14, 20);
                    doc.setFontSize(9);
                    doc.setFont("helvetica", "normal");
                    doc.text(carrier.slice(0, 32), 14, 34);
                    doc.text("POSTAGE PAID", 274, 26, { align: "right" });

                    // From
                    doc.setTextColor(50, 50, 50);
                    doc.setFontSize(7);
                    doc.setFont("helvetica", "bold");
                    doc.text("FROM:", 14, 54);
                    doc.setFont("helvetica", "normal");
                    doc.text("Watani & Sons Corp · 300 Greenbank Rd, Ottawa, ON K2H 0B6", 14, 64);
                    doc.text("Tel: +1 613-854-7777 · Info@wataniandsons.com", 14, 73);

                    doc.setDrawColor(200, 200, 200);
                    doc.line(14, 78, 274, 78);

                    // Ship To
                    doc.setFontSize(8);
                    doc.setFont("helvetica", "bold");
                    doc.text("SHIP TO:", 14, 90);
                    doc.setFontSize(11);
                    doc.setTextColor(0, 0, 0);
                    doc.text((addr.fullName || order.email || "Customer").slice(0, 32), 14, 105);
                    doc.setFontSize(10);
                    doc.setFont("helvetica", "normal");
                    doc.text((addr.line1 || "").slice(0, 36), 14, 118);
                    if (addr.line2) doc.text((addr.line2 || "").slice(0, 36), 14, 130);
                    doc.setFont("helvetica", "bold");
                    doc.setFontSize(12);
                    doc.text(`${destCity}, ${destRegion}  ${destPostal}`, 14, addr.line2 ? 146 : 134);
                    doc.setFontSize(9);
                    doc.text("CANADA", 14, addr.line2 ? 158 : 146);

                    // Postal Code Box
                    doc.setDrawColor(0, 0, 0);
                    doc.setLineWidth(1.5);
                    doc.rect(190, 88, 84, 50);
                    doc.setFontSize(8);
                    doc.text("POSTAL CODE", 232, 100, { align: "center" });
                    doc.setFontSize(13);
                    doc.text(destPostal, 232, 122, { align: "center" });

                    // Package details
                    const yBox = 175;
                    doc.setDrawColor(220, 220, 220);
                    doc.line(14, yBox, 274, yBox);
                    doc.setFontSize(8);
                    doc.setFont("helvetica", "normal");
                    doc.setTextColor(80, 80, 80);
                    doc.text(`BOX ${idx + 1} OF ${boxesToPrint.length}`, 14, yBox + 12);
                    doc.text(`WT: ${boxWtKg} kg (${boxWtLbs} lbs)`, 95, yBox + 12);
                    doc.text(`DIM: ${box.lengthIn || 12}"×${box.widthIn || 10}"×${box.heightIn || 8}"`, 185, yBox + 12);
                    doc.text(`ORDER: ${order.orderNumber}`, 14, yBox + 24);
                    doc.text(`DATE: ${placedDate}`, 185, yBox + 24);

                    // Tracking area
                    doc.setDrawColor(0, 0, 0);
                    doc.line(14, yBox + 32, 274, yBox + 32);
                    doc.setFontSize(8);
                    doc.setFont("helvetica", "bold");
                    doc.setTextColor(0, 0, 0);
                    doc.text("CARRIER TRACKING NUMBER / CODE 128", 144, yBox + 46, { align: "center" });
                    doc.setFontSize(13);
                    doc.setFont("courier", "bold");
                    doc.text(trackingNum, 144, yBox + 130, { align: "center" });

                    // Barcode placeholder text in PDF (SVG prints directly on browser print)
                    doc.setFont("helvetica", "normal");
                    doc.setFontSize(7);
                    doc.setTextColor(120, 120, 120);
                    doc.text("* SCANNABLE FREIGHTCOM BARCODE *", 144, yBox + 145, { align: "center" });

                    // Footer
                    doc.line(14, 400, 274, 400);
                    doc.setFontSize(7);
                    doc.text("FOOD GRADE CARGO · HANDLE WITH CARE · PROTECT FROM FREEZING", 144, 412, { align: "center" });
                });

                doc.save(`shipping-label-${order.orderNumber}.pdf`);
            } else if (docType === "PALLET") {
                // Letter format (612 x 792 pt)
                const doc = new jsPDF({ unit: "pt", format: "letter" });
                const boxesToPrint = selectedBoxIndex === -1 ? displayBoxes : [displayBoxes[selectedBoxIndex]];

                boxesToPrint.forEach((box, idx) => {
                    if (idx > 0) doc.addPage("letter");
                    doc.setFillColor(15, 45, 40);
                    doc.rect(0, 0, 612, 70, "F");
                    doc.setTextColor(255, 255, 255);
                    doc.setFont("helvetica", "bold");
                    doc.setFontSize(22);
                    doc.text("PALLET / SKID SHIPMENT PLACARD", 40, 42);

                    doc.setTextColor(0, 0, 0);
                    doc.setFontSize(28);
                    doc.text(`SKID ${idx + 1} OF ${boxesToPrint.length}`, 40, 115);
                    doc.setFontSize(14);
                    doc.text(`CARRIER: ${carrier.toUpperCase()}`, 40, 140);
                    doc.text(`PRO / TRACKING: ${trackingNum}`, 40, 160);

                    // Consignee
                    doc.setDrawColor(0, 0, 0);
                    doc.setLineWidth(2);
                    doc.rect(40, 180, 532, 170);
                    doc.setFontSize(12);
                    doc.text("DELIVERY DESTINATION / CONSIGNEE:", 55, 205);
                    doc.setFontSize(20);
                    doc.text((addr.fullName || order.email || "Customer").toUpperCase(), 55, 235);
                    doc.setFontSize(16);
                    doc.setFont("helvetica", "normal");
                    doc.text(addr.line1 || "", 55, 260);
                    if (addr.line2) doc.text(addr.line2, 55, 280);
                    doc.setFont("helvetica", "bold");
                    doc.setFontSize(22);
                    doc.text(`${destCity}, ${destRegion}  ${destPostal}`, 55, addr.line2 ? 310 : 295);

                    // Warning banners
                    doc.setFillColor(254, 226, 226);
                    doc.rect(40, 370, 532, 60, "F");
                    doc.setTextColor(185, 28, 28);
                    doc.setFontSize(18);
                    doc.text("⚠️ DO NOT DOUBLE STACK — TOP LOAD ONLY", 306, 406, { align: "center" });

                    // Details
                    doc.setTextColor(0, 0, 0);
                    doc.setFontSize(14);
                    doc.text("SKID SPECIFICATIONS:", 40, 465);
                    doc.setFont("helvetica", "normal");
                    doc.setFontSize(12);
                    doc.text("• Dimensions: 40\" × 48\" Standard GMA Wooden Pallet", 55, 490);
                    doc.text(`• Gross Pallet Weight: ${totalWeightKg.toFixed(1)} kg (${totalWeightLbs} lbs)`, 55, 510);
                    doc.text("• Cargo: Palestinian Premium Olive Oil & Fine Foods", 55, 530);
                    doc.text(`• Order Number: #${order.orderNumber} · Ship Date: ${placedDate}`, 55, 550);

                    // Shipper
                    doc.setFont("helvetica", "bold");
                    doc.text("SHIPPER / ORIGIN:", 40, 600);
                    doc.setFont("helvetica", "normal");
                    doc.text("WATANI & SONS CORP · 300 Greenbank Rd, Ottawa, ON K2H 0B6 · Tel: +1 613-854-7777", 40, 620);

                    doc.line(40, 680, 572, 680);
                    doc.setFontSize(10);
                    doc.text("Affix this placard securely to all 4 sides of the shrink-wrapped skid.", 306, 705, { align: "center" });
                });

                doc.save(`pallet-placard-${order.orderNumber}.pdf`);
            } else {
                // BOL Format (612 x 792 pt)
                const doc = new jsPDF({ unit: "pt", format: "letter" });
                doc.setFillColor(15, 45, 40);
                doc.rect(0, 0, 612, 60, "F");
                doc.setTextColor(255, 255, 255);
                doc.setFont("helvetica", "bold");
                doc.setFontSize(18);
                doc.text("STRAIGHT BILL OF LADING — SHORT FORM", 40, 36);
                doc.setFontSize(11);
                doc.text(`BOL #: BOL-${order.orderNumber}`, 572, 36, { align: "right" });

                doc.setTextColor(0, 0, 0);
                doc.setFontSize(10);
                doc.text(`Date: ${placedDate}`, 40, 80);
                doc.text(`Carrier: ${carrier}`, 240, 80);
                doc.text(`Trailer / PRO #: ${trackingNum}`, 430, 80);

                // Shipper & Consignee columns
                doc.setDrawColor(0, 0, 0);
                doc.setLineWidth(1);
                doc.rect(40, 95, 260, 110);
                doc.rect(312, 95, 260, 110);

                doc.setFont("helvetica", "bold");
                doc.text("SHIPPER (ORIGIN):", 50, 112);
                doc.setFont("helvetica", "normal");
                doc.text("Watani & Sons Corp", 50, 128);
                doc.text("300 Greenbank Rd", 50, 142);
                doc.text("Ottawa, ON K2H 0B6, Canada", 50, 156);
                doc.text("Phone: +1 613-854-7777", 50, 170);
                doc.text("Email: Info@wataniandsons.com", 50, 184);

                doc.setFont("helvetica", "bold");
                doc.text("CONSIGNEE (DELIVER TO):", 322, 112);
                doc.setFont("helvetica", "normal");
                doc.text(addr.fullName || order.email || "Customer", 322, 128);
                doc.text(addr.line1 || "", 322, 142);
                if (addr.line2) doc.text(addr.line2, 322, 156);
                doc.text(`${destCity}, ${destRegion}  ${destPostal}`, 322, addr.line2 ? 170 : 156);
                doc.text("Phone: " + (addr.phone || "On File"), 322, addr.line2 ? 184 : 170);

                // Table
                let y = 220;
                doc.setFillColor(240, 240, 240);
                doc.rect(40, y, 532, 22, "F");
                doc.setFont("helvetica", "bold");
                doc.setFontSize(9);
                doc.text("HANDLING UNITS", 50, y + 15);
                doc.text("PACKAGE TYPE", 160, y + 15);
                doc.text("COMMODITY DESCRIPTION", 260, y + 15);
                doc.text("WEIGHT (KG)", 460, y + 15);
                doc.text("WEIGHT (LBS)", 520, y + 15);

                y += 22;
                doc.setFont("helvetica", "normal");
                doc.text(`${displayBoxes.length}`, 50, y + 20);
                doc.text(isPalletShipment ? "GMA Pallet (40x48)" : "Cartons / Boxes", 160, y + 20);
                doc.text("Foodstuffs - Extra Virgin Olive Oil & Goods", 260, y + 15);
                doc.setFontSize(8);
                doc.setTextColor(100, 100, 100);
                doc.text("NMFC: 073220 · Class: 65 · Non-Hazardous", 260, y + 27);
                doc.setTextColor(0, 0, 0);
                doc.setFontSize(9);
                doc.text(totalWeightKg.toFixed(1), 460, y + 20);
                doc.text(totalWeightLbs, 520, y + 20);

                // Signatures
                y = 520;
                doc.line(40, y, 572, y);
                doc.setFontSize(8);
                doc.text("FREIGHT CHARGES: [ X ] PREPAID     [   ] COLLECT     [   ] THIRD PARTY", 40, y + 18);

                y += 40;
                doc.rect(40, y, 170, 70);
                doc.rect(220, y, 170, 70);
                doc.rect(400, y, 170, 70);

                doc.setFont("helvetica", "bold");
                doc.text("SHIPPER CERTIFICATION", 45, y + 14);
                doc.setFont("helvetica", "normal");
                doc.setFontSize(7);
                doc.text("Watani & Sons Corp", 45, y + 30);
                doc.text("Sign: ____________________", 45, y + 50);
                doc.text(`Date: ${placedDate}`, 45, y + 62);

                doc.setFont("helvetica", "bold");
                doc.setFontSize(8);
                doc.text("CARRIER RECEIPT", 225, y + 14);
                doc.setFont("helvetica", "normal");
                doc.setFontSize(7);
                doc.text(`Driver Name: _________________`, 225, y + 30);
                doc.text("Sign: ____________________", 225, y + 50);
                doc.text(`Date: ____________________`, 225, y + 62);

                doc.setFont("helvetica", "bold");
                doc.setFontSize(8);
                doc.text("CONSIGNEE ACCEPTANCE", 405, y + 14);
                doc.setFont("helvetica", "normal");
                doc.setFontSize(7);
                doc.text("Received in good order except as noted", 405, y + 28);
                doc.text("Sign: ____________________", 405, y + 50);
                doc.text("Date: ____________________", 405, y + 62);

                doc.save(`bill-of-lading-${order.orderNumber}.pdf`);
            }
        } catch (e) {
            console.error("PDF generation failed:", e);
        } finally {
            setDownloadingPdf(false);
        }
    }

    return (
        <div className="shipping-label-container w-full">
            {/* Action Bar (Hidden on print) */}
            <div className="print:hidden mb-6 flex flex-wrap items-center justify-between gap-4 rounded-2xl bg-white p-4 shadow-card border border-teal-950/10">
                <div className="flex flex-wrap items-center gap-2">
                    {onClose && (
                        <button
                            type="button"
                            onClick={onClose}
                            className="inline-flex items-center gap-1.5 rounded-xl border border-black/10 px-3 py-2 text-[13px] font-semibold text-teal-950 hover:bg-soft-control transition-colors"
                        >
                            <ArrowLeft className="size-4" />
                            Back to Order
                        </button>
                    )}

                    <div className="inline-flex rounded-xl bg-soft-control p-1 border border-black/5">
                        <button
                            type="button"
                            onClick={() => setDocType("PARCEL")}
                            className={`flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-[12px] font-bold transition-all ${
                                docType === "PARCEL"
                                    ? "bg-teal-950 text-white shadow-xs"
                                    : "text-teal-950 hover:bg-black/5"
                            }`}
                        >
                            <Truck className="size-3.5" />
                            Parcel Label (4×6)
                        </button>
                        <button
                            type="button"
                            onClick={() => setDocType("PALLET")}
                            className={`flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-[12px] font-bold transition-all ${
                                docType === "PALLET"
                                    ? "bg-teal-950 text-white shadow-xs"
                                    : "text-teal-950 hover:bg-black/5"
                            }`}
                        >
                            <Box className="size-3.5" />
                            Pallet Placard (8.5×11)
                        </button>
                        <button
                            type="button"
                            onClick={() => setDocType("BOL")}
                            className={`flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-[12px] font-bold transition-all ${
                                docType === "BOL"
                                    ? "bg-teal-950 text-white shadow-xs"
                                    : "text-teal-950 hover:bg-black/5"
                            }`}
                        >
                            <FileText className="size-3.5" />
                            Bill of Lading (BOL)
                        </button>
                    </div>

                    {displayBoxes.length > 1 && docType !== "BOL" && (
                        <select
                            value={selectedBoxIndex}
                            onChange={(e) => setSelectedBoxIndex(Number(e.target.value))}
                            className="h-9 rounded-xl border border-black/15 bg-white px-3 text-[12px] font-semibold text-teal-950 focus:border-teal-950 focus:outline-none"
                        >
                            <option value={-1}>All {docType === "PALLET" ? "Pallets / Skids" : "Boxes"} ({displayBoxes.length})</option>
                            {displayBoxes.map((_, i) => (
                                <option key={i} value={i}>
                                    {docType === "PALLET" ? "Skid" : "Box"} {i + 1} of {displayBoxes.length}
                                </option>
                            ))}
                        </select>
                    )}
                </div>

                <div className="flex items-center gap-2">
                    <button
                        type="button"
                        disabled={downloadingPdf}
                        onClick={handleDownloadPdf}
                        className="inline-flex items-center gap-1.5 rounded-xl border border-black/15 bg-white px-3.5 py-2 text-[13px] font-bold text-teal-950 hover:bg-soft-control shadow-xs transition-colors disabled:opacity-50"
                    >
                        <Download className="size-4" />
                        {downloadingPdf ? "Saving PDF…" : "Download PDF"}
                    </button>
                    <button
                        type="button"
                        onClick={handlePrint}
                        className="inline-flex items-center gap-1.5 rounded-xl bg-teal-950 px-4 py-2 text-[13px] font-bold text-white shadow-xs hover:bg-teal-900 transition-colors"
                    >
                        <Printer className="size-4" />
                        Print Document
                    </button>
                </div>
            </div>

            {/* Print Stylesheet */}
            <style jsx global>{`
                @media print {
                    @page {
                        margin: 0;
                        size: ${docType === "PARCEL" ? "4in 6in" : "letter portrait"};
                    }
                    body {
                        background: white !important;
                        color: black !important;
                    }
                    .shipping-label-container {
                        width: 100% !important;
                        margin: 0 !important;
                        padding: 0 !important;
                    }
                    .label-page {
                        page-break-after: always;
                        break-after: page;
                        margin: 0 !important;
                        box-shadow: none !important;
                        border: none !important;
                    }
                    .print\\:hidden {
                        display: none !important;
                    }
                }
            `}</style>

            {/* Printable Content Area */}
            <div className="flex flex-col items-center gap-8 py-2">
                {/* 1. PARCEL SHIPPING LABELS (4" x 6" Thermal Format) */}
                {docType === "PARCEL" && (
                    (selectedBoxIndex === -1 ? displayBoxes : [displayBoxes[selectedBoxIndex]]).map((box, idx) => {
                        const effectiveIdx = selectedBoxIndex === -1 ? idx : selectedBoxIndex;
                        const boxWtKg = ((box.weightGrams || 1000) / 1000).toFixed(1);
                        const boxWtLbs = (((box.weightGrams || 1000) / 1000) * 2.20462).toFixed(1);

                        return (
                            <div
                                key={box.id || idx}
                                className="label-page w-[400px] min-h-[600px] bg-white border-2 border-black rounded-sm p-4 font-sans text-black flex flex-col justify-between shadow-lg"
                                style={{ width: "4in", height: "6in", boxSizing: "border-box" }}
                            >
                                <div>
                                    {/* Top Header */}
                                    <div className="flex items-center justify-between border-b-2 border-black pb-2">
                                        <div>
                                            <div className="flex items-center gap-1.5">
                                                <div className="size-4 rounded-full bg-teal-950" />
                                                <span className="font-extrabold text-[15px] tracking-tight text-teal-950">WATANI &amp; SONS</span>
                                            </div>
                                            <p className="text-[10px] font-bold uppercase tracking-wider text-neutral-700 mt-0.5">
                                                {carrier}
                                            </p>
                                        </div>
                                        <div className="text-right">
                                            <span className="inline-block border border-black px-1.5 py-0.5 text-[9px] font-black uppercase">
                                                POSTAGE PAID
                                            </span>
                                            <p className="text-[10px] font-bold text-neutral-800 mt-0.5">{serviceName}</p>
                                        </div>
                                    </div>

                                    {/* Shipper (Origin) */}
                                    <div className="pt-2 pb-1.5 border-b border-black/20 text-[9px] leading-tight text-neutral-600">
                                        <span className="font-bold text-black">FROM:</span> Watani &amp; Sons Corp · 300 Greenbank Rd, Ottawa, ON K2H 0B6 · +1 613-854-7777
                                    </div>

                                    {/* Consignee (Deliver To) */}
                                    <div className="grid grid-cols-3 gap-2 py-3 border-b-2 border-black">
                                        <div className="col-span-2">
                                            <span className="text-[10px] font-extrabold uppercase text-neutral-500 tracking-wider">
                                                DELIVER TO:
                                            </span>
                                            <p className="text-[15px] font-extrabold text-black leading-snug mt-0.5">
                                                {addr.fullName || order.email || "Customer"}
                                            </p>
                                            <p className="text-[12px] font-bold text-neutral-900 mt-0.5 leading-snug">
                                                {addr.line1}
                                                {addr.line2 ? `, ${addr.line2}` : ""}
                                            </p>
                                            <p className="text-[14px] font-black text-black mt-1">
                                                {destCity}, {destRegion}  {destPostal}
                                            </p>
                                            <p className="text-[11px] font-bold text-neutral-700 uppercase">{destCountry}</p>
                                            {addr.phone && (
                                                <p className="text-[10px] text-neutral-600 mt-0.5 font-mono">Tel: {addr.phone}</p>
                                            )}
                                        </div>

                                        {/* Postal Code Routing Stamp */}
                                        <div className="border-2 border-black flex flex-col items-center justify-center p-1 text-center bg-neutral-50">
                                            <span className="text-[9px] font-black uppercase tracking-wider text-neutral-700">POSTAL</span>
                                            <p className="text-[15px] font-black tracking-tight text-black mt-0.5">{destPostal}</p>
                                            <span className="text-[8px] font-mono text-neutral-500 mt-0.5">ZONE CA-ON</span>
                                        </div>
                                    </div>

                                    {/* Package Specs */}
                                    <div className="grid grid-cols-3 text-[10px] py-1.5 border-b border-black/30 font-medium">
                                        <div>
                                            <span className="text-neutral-500">PACKAGE:</span>{" "}
                                            <strong className="text-black font-black">BOX {effectiveIdx + 1} OF {displayBoxes.length}</strong>
                                        </div>
                                        <div>
                                            <span className="text-neutral-500">WEIGHT:</span>{" "}
                                            <strong className="text-black">{boxWtKg} kg ({boxWtLbs} lb)</strong>
                                        </div>
                                        <div className="text-right">
                                            <span className="text-neutral-500">DIM:</span>{" "}
                                            <strong>{box.lengthIn || 12}&quot;×{box.widthIn || 10}&quot;×{box.heightIn || 8}&quot;</strong>
                                        </div>
                                    </div>

                                    <div className="flex justify-between text-[10px] py-1 border-b-2 border-black">
                                        <span>ORDER #: <strong className="font-mono">{order.orderNumber}</strong></span>
                                        <span>DATE: <strong>{placedDate}</strong></span>
                                    </div>

                                    {/* Main Tracking Barcode Section */}
                                    <div className="pt-4 pb-2 flex flex-col items-center">
                                        <span className="text-[10px] font-black uppercase tracking-widest text-neutral-800 mb-1">
                                            CARRIER TRACKING BARCODE
                                        </span>
                                        <BarcodeSvg
                                            value={trackingNum}
                                            height={65}
                                            barWidth={1.7}
                                            showText={true}
                                            label={trackingNum}
                                        />
                                    </div>
                                </div>

                                {/* Bottom Notice */}
                                <div className="border-t border-black/30 pt-1.5 text-center text-[8px] font-bold uppercase tracking-wider text-neutral-600">
                                    PALESTINIAN FOOD PRODUCTS · HANDLE WITH CARE · PROTECT FROM FREEZING
                                </div>
                            </div>
                        );
                    })
                )}

                {/* 2. PALLET / SKID SHIPMENT PLACARDS (8.5" x 11" Letter Format) */}
                {docType === "PALLET" && (
                    (selectedBoxIndex === -1 ? displayBoxes : [displayBoxes[selectedBoxIndex]]).map((box, idx) => {
                        const effectiveIdx = selectedBoxIndex === -1 ? idx : selectedBoxIndex;

                        return (
                            <div
                                key={box.id || idx}
                                className="label-page w-[800px] min-h-[1050px] bg-white border-4 border-black p-8 font-sans text-black flex flex-col justify-between shadow-lg"
                                style={{ width: "8.5in", height: "11in", boxSizing: "border-box" }}
                            >
                                <div>
                                    {/* Pallet Placard Big Header */}
                                    <div className="border-b-4 border-black pb-4 flex items-center justify-between">
                                        <div>
                                            <div className="flex items-center gap-2">
                                                <div className="size-6 rounded-md bg-teal-950" />
                                                <span className="font-black text-[24px] tracking-tight text-teal-950">WATANI &amp; SONS CORP</span>
                                            </div>
                                            <p className="text-[13px] font-extrabold uppercase text-neutral-600 mt-1 tracking-wider">
                                                LTL FREIGHT LOGISTICS DIVISION · CANADA
                                            </p>
                                        </div>
                                        <div className="text-right">
                                            <span className="inline-block bg-black text-white px-3 py-1 text-[13px] font-black uppercase tracking-wider">
                                                GMA 40&quot;×48&quot; PALLET
                                            </span>
                                            <p className="text-[13px] font-mono font-bold mt-1 text-neutral-800">#{order.orderNumber}</p>
                                        </div>
                                    </div>

                                    {/* Huge Skid Count Header */}
                                    <div className="bg-neutral-900 text-white p-4 text-center my-4 rounded-sm">
                                        <h1 className="text-[38px] font-black uppercase tracking-wider">
                                            PALLET SKID {effectiveIdx + 1} OF {displayBoxes.length}
                                        </h1>
                                        <p className="text-[15px] font-bold text-neutral-300 mt-0.5 uppercase tracking-wide">
                                            CARRIER: {carrier.toUpperCase()}
                                        </p>
                                    </div>

                                    {/* Destination Address Container */}
                                    <div className="border-4 border-black p-6 my-4 bg-white">
                                        <span className="text-[12px] font-black uppercase tracking-wider text-neutral-500">
                                            DELIVERY DESTINATION / CONSIGNEE:
                                        </span>
                                        <h2 className="text-[26px] font-black text-black mt-1 leading-tight">
                                            {addr.fullName || order.email || "Customer"}
                                        </h2>
                                        <p className="text-[18px] font-bold text-neutral-900 mt-1">
                                            {addr.line1}
                                            {addr.line2 ? `, ${addr.line2}` : ""}
                                        </p>
                                        <div className="flex items-baseline justify-between mt-3 pt-3 border-t-2 border-black">
                                            <p className="text-[28px] font-black text-black tracking-tight">
                                                {destCity}, {destRegion}
                                            </p>
                                            <p className="text-[34px] font-black text-black font-mono tracking-wider">
                                                {destPostal}
                                            </p>
                                        </div>
                                        <p className="text-[14px] font-bold uppercase text-neutral-700 mt-1">{destCountry}</p>
                                    </div>

                                    {/* Skid Warning Badges */}
                                    <div className="grid grid-cols-2 gap-4 my-4">
                                        <div className="border-3 border-rose-600 bg-rose-50 p-3 text-center rounded-sm">
                                            <span className="text-[20px] font-black text-rose-800 block uppercase">
                                                ⚠️ DO NOT DOUBLE STACK
                                            </span>
                                            <span className="text-[12px] font-bold text-rose-700">TOP LOAD ONLY — GLASS / BOTTLES</span>
                                        </div>
                                        <div className="border-3 border-emerald-600 bg-emerald-50 p-3 text-center rounded-sm">
                                            <span className="text-[20px] font-black text-emerald-800 block uppercase">
                                                🛡️ FOOD GRADE CARGO
                                            </span>
                                            <span className="text-[12px] font-bold text-emerald-700">KEEP DRY · CLEAN TRAILER REQUIRED</span>
                                        </div>
                                    </div>

                                    {/* Skid Specifications Table */}
                                    <div className="border-2 border-black my-4 text-[13px]">
                                        <div className="grid grid-cols-4 bg-neutral-100 font-bold p-2 border-b border-black text-neutral-700">
                                            <div>SKID FOOTPRINT</div>
                                            <div>GROSS WEIGHT</div>
                                            <div>CONTENT SUMMARY</div>
                                            <div className="text-right">SHIP DATE</div>
                                        </div>
                                        <div className="grid grid-cols-4 p-2.5 font-semibold text-black">
                                            <div>Standard 40&quot; × 48&quot; GMA</div>
                                            <div className="font-bold">{totalWeightKg.toFixed(1)} kg ({totalWeightLbs} lbs)</div>
                                            <div>Palestinian Olive Oil / Groceries</div>
                                            <div className="text-right font-mono">{placedDate}</div>
                                        </div>
                                    </div>

                                    {/* Large Scannable PRO / Barcode */}
                                    <div className="mt-6 flex flex-col items-center justify-center p-4 border-2 border-dashed border-black/40">
                                        <span className="text-[11px] font-black uppercase tracking-widest text-neutral-800 mb-1">
                                            PRO / TRACKING BARCODE (CODE 128)
                                        </span>
                                        <BarcodeSvg
                                            value={trackingNum}
                                            height={80}
                                            barWidth={2.4}
                                            showText={true}
                                            label={trackingNum}
                                        />
                                    </div>
                                </div>

                                {/* Shipper Footer */}
                                <div className="border-t-2 border-black pt-3 text-center text-[11px] text-neutral-600">
                                    <p className="font-bold text-black">
                                        SHIPPER: WATANI &amp; SONS CORP · 300 Greenbank Rd, Ottawa, ON K2H 0B6 · Tel: +1 613-854-7777 · Info@wataniandsons.com
                                    </p>
                                    <p className="text-[10px] text-neutral-500 mt-0.5">
                                        Affix this placard visibly to all 4 sides of the shrink-wrapped pallet skid prior to freight carrier pickup.
                                    </p>
                                </div>
                            </div>
                        );
                    })
                )}

                {/* 3. OFFICIAL BILL OF LADING (BOL - 8.5" x 11" Letter Format) */}
                {docType === "BOL" && (
                    <div
                        className="label-page w-[800px] min-h-[1050px] bg-white border-2 border-black p-8 font-sans text-black flex flex-col justify-between shadow-lg"
                        style={{ width: "8.5in", height: "11in", boxSizing: "border-box" }}
                    >
                        <div>
                            {/* BOL Header */}
                            <div className="border-b-2 border-black pb-3 flex items-start justify-between">
                                <div>
                                    <h1 className="text-[20px] font-black tracking-tight text-teal-950">
                                        STRAIGHT BILL OF LADING — SHORT FORM
                                    </h1>
                                    <p className="text-[11px] font-bold text-neutral-600 uppercase">
                                        Original — Not Negotiable · Canadian Domestic LTL Freight
                                    </p>
                                </div>
                                <div className="text-right">
                                    <div className="border-2 border-black px-3 py-1">
                                        <span className="text-[10px] font-bold text-neutral-600 block uppercase">BOL NUMBER</span>
                                        <span className="text-[16px] font-mono font-black">BOL-{order.orderNumber}</span>
                                    </div>
                                    <p className="text-[11px] font-semibold text-neutral-700 mt-1">Date: {placedDate}</p>
                                </div>
                            </div>

                            {/* Carrier & Routing */}
                            <div className="grid grid-cols-3 gap-2 py-2 border-b border-black text-[12px]">
                                <div>
                                    <span className="text-[10px] font-bold text-neutral-500 uppercase">CARRIER:</span>
                                    <p className="font-bold text-black">{carrier}</p>
                                </div>
                                <div>
                                    <span className="text-[10px] font-bold text-neutral-500 uppercase">TRAILER / PRO #:</span>
                                    <p className="font-mono font-bold text-black">{trackingNum}</p>
                                </div>
                                <div>
                                    <span className="text-[10px] font-bold text-neutral-500 uppercase">PAYMENT TERMS:</span>
                                    <p className="font-bold text-black uppercase">Prepaid by Shipper</p>
                                </div>
                            </div>

                            {/* Shipper & Consignee Columns */}
                            <div className="grid grid-cols-2 gap-4 py-3 border-b-2 border-black text-[12px]">
                                <div className="border border-black p-3 rounded-xs bg-neutral-50/50">
                                    <span className="text-[10px] font-black uppercase text-neutral-600 tracking-wider">
                                        SHIPPER / ORIGIN (FROM):
                                    </span>
                                    <p className="font-extrabold text-[14px] text-black mt-1">WATANI &amp; SONS CORP</p>
                                    <p className="text-neutral-800">300 Greenbank Rd</p>
                                    <p className="text-neutral-800 font-semibold">Ottawa, ON K2H 0B6, Canada</p>
                                    <p className="text-neutral-600 mt-1">Phone: +1 613-854-7777</p>
                                    <p className="text-neutral-600">Email: Info@wataniandsons.com</p>
                                </div>

                                <div className="border border-black p-3 rounded-xs bg-neutral-50/50">
                                    <span className="text-[10px] font-black uppercase text-neutral-600 tracking-wider">
                                        CONSIGNEE / DESTINATION (SHIP TO):
                                    </span>
                                    <p className="font-extrabold text-[14px] text-black mt-1">
                                        {addr.fullName || order.email || "Customer"}
                                    </p>
                                    <p className="text-neutral-800">{addr.line1}</p>
                                    {addr.line2 && <p className="text-neutral-800">{addr.line2}</p>}
                                    <p className="font-black text-black text-[14px] mt-0.5">
                                        {destCity}, {destRegion}  {destPostal}
                                    </p>
                                    <p className="text-neutral-600 mt-1">Phone: {addr.phone || "On File"}</p>
                                </div>
                            </div>

                            {/* Special Delivery Instructions */}
                            <div className="py-2 border-b border-black text-[11px]">
                                <span className="font-bold text-black uppercase">SPECIAL INSTRUCTIONS: </span>
                                <span className="text-neutral-800">
                                    Food Grade Pallet. Do Not Double Stack. Standard commercial loading dock or liftgate delivery. Call consignee 24 hours prior to scheduled delivery.
                                </span>
                            </div>

                            {/* Freight Commodities Table */}
                            <div className="mt-3 border border-black text-[11px]">
                                <div className="grid grid-cols-12 bg-neutral-100 font-bold p-2 border-b border-black text-neutral-800">
                                    <div className="col-span-2">HANDLING UNITS</div>
                                    <div className="col-span-2">PACKAGE TYPE</div>
                                    <div className="col-span-5">COMMODITY DESCRIPTION / NMFC</div>
                                    <div className="col-span-3 text-right">WEIGHT (KG / LBS)</div>
                                </div>

                                <div className="grid grid-cols-12 p-2.5 border-b border-black/20 items-center font-medium">
                                    <div className="col-span-2 font-bold text-[14px]">
                                        {displayBoxes.length} {isPalletShipment ? "Skid(s)" : "Carton(s)"}
                                    </div>
                                    <div className="col-span-2">
                                        {isPalletShipment ? "GMA Pallet 40\"×48\"" : "Corrugated Boxes"}
                                    </div>
                                    <div className="col-span-5">
                                        <p className="font-bold text-black">Palestinian Premium Olive Oil &amp; Specialty Groceries</p>
                                        <p className="text-[10px] text-neutral-600">NMFC: 073220 · Freight Class: 65 · Non-Hazardous Food</p>
                                    </div>
                                    <div className="col-span-3 text-right font-mono font-bold text-[13px]">
                                        {totalWeightKg.toFixed(1)} kg / {totalWeightLbs} lbs
                                    </div>
                                </div>

                                {(order.items || []).slice(0, 4).map((line) => (
                                    <div key={line.sku} className="grid grid-cols-12 px-2.5 py-1 text-[10px] text-neutral-600">
                                        <div className="col-span-2">×{line.quantity} units</div>
                                        <div className="col-span-2">{line.sku}</div>
                                        <div className="col-span-5 truncate">{line.productName} ({line.unit})</div>
                                        <div className="col-span-3 text-right font-mono">
                                            {(((line.unitWeightGrams || 1000) * line.quantity) / 1000).toFixed(1)} kg
                                        </div>
                                    </div>
                                ))}

                                <div className="grid grid-cols-12 p-2 bg-neutral-50 font-bold border-t border-black text-black">
                                    <div className="col-span-9 uppercase">TOTAL PIECES / WEIGHT:</div>
                                    <div className="col-span-3 text-right font-mono font-black text-[13px]">
                                        {totalWeightKg.toFixed(1)} kg ({totalWeightLbs} lbs)
                                    </div>
                                </div>
                            </div>

                            {/* Standard Legal Certification */}
                            <div className="mt-3 text-[9px] text-neutral-600 leading-tight">
                                <p>
                                    RECEIVED, subject to individually determined rates or contracts that have been agreed upon in writing between the carrier and shipper, the property described above, in apparent good order, except as noted. This shipping order is not a Bill of Lading, but an acknowledgment that a Bill of Lading has been issued and is subject to all terms and conditions of standard Canadian uniform freight classification.
                                </p>
                            </div>
                        </div>

                        {/* Signatures & Certification Area */}
                        <div>
                            <div className="grid grid-cols-3 gap-3 pt-4 border-t-2 border-black text-[10px]">
                                <div className="border border-black p-2.5 flex flex-col justify-between h-28">
                                    <span className="font-bold text-black uppercase">SHIPPER CERTIFICATION:</span>
                                    <p className="text-[9px] text-neutral-500">
                                        Certified properly packaged, marked, and labeled.
                                    </p>
                                    <div className="border-b border-black mt-2" />
                                    <div className="flex justify-between text-[9px] font-semibold text-neutral-700">
                                        <span>Watani &amp; Sons Corp</span>
                                        <span>Date: {placedDate}</span>
                                    </div>
                                </div>

                                <div className="border border-black p-2.5 flex flex-col justify-between h-28">
                                    <span className="font-bold text-black uppercase">CARRIER RECEIPT:</span>
                                    <p className="text-[9px] text-neutral-500">
                                        Driver received {displayBoxes.length} piece(s) in good order.
                                    </p>
                                    <div className="border-b border-black mt-2" />
                                    <div className="flex justify-between text-[9px] font-semibold text-neutral-700">
                                        <span>Driver Signature</span>
                                        <span>Date: _________</span>
                                    </div>
                                </div>

                                <div className="border border-black p-2.5 flex flex-col justify-between h-28">
                                    <span className="font-bold text-black uppercase">CONSIGNEE ACCEPTANCE:</span>
                                    <p className="text-[9px] text-neutral-500">
                                        Received complete shipment without exception.
                                    </p>
                                    <div className="border-b border-black mt-2" />
                                    <div className="flex justify-between text-[9px] font-semibold text-neutral-700">
                                        <span>Receiver Signature</span>
                                        <span>Date: _________</span>
                                    </div>
                                </div>
                            </div>

                            <div className="pt-2 text-center text-[9px] text-neutral-500">
                                Watani &amp; Sons Corp · Official Bill of Lading · Generated for Order #{order.orderNumber}
                            </div>
                        </div>
                    </div>
                )}
            </div>
        </div>
    );
}
